jobs:
  - job: 'OSX'
    strategy:
      matrix:
        macOS_10_15:
          image_name: 'macOS-10.15'
          HG_USE_TBB: 'Off'
        macOS_10_15_TBB:
          image_name: 'macOS-10.15'
          HG_USE_TBB: 'On'
    pool:
      vmImage: $(image_name)
    variables:
      CC: clang
      CXX: clang++
    timeoutInMinutes: 360
    steps:

      - script: |
          echo "Removing homebrew for Azure to avoid conflicts with conda"
          curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
          chmod +x ~/uninstall_homebrew
          ~/uninstall_homebrew -f -q
        displayName: Remove homebrew

      - bash: |
          echo "##vso[task.prependpath]$CONDA/bin"
          sudo chown -R $USER $CONDA
        displayName: Add conda to PATH

      - script: |
          conda config --set always_yes yes --set changeps1 no
          conda update -q conda
          conda install cmake tbb-devel==2019.9 scikit-learn==1.0.1 -c conda-forge
        displayName: Install python packages

      - script: |
          set -e
          mkdir build
          cd build
          MAKE_TARGETS="test_exe higram"
          CMAKE_EXTRA_ARGS="$CMAKE_EXTRA_ARGS -DPYTHON_EXECUTABLE:FILEPATH=$CONDA/bin/python -DTBB_INCLUDE_DIR=$CONDA/include -DTBB_LIBRARY=$CONDA/lib -DHG_USE_TBB=$HG_USE_TBB";
          CMAKE_EXTRA_ARGS="$CMAKE_EXTRA_ARGS -DCMAKE_BUILD_TYPE=Debug"
          cmake $CMAKE_EXTRA_ARGS $(Build.SourcesDirectory)
          make -j2 $MAKE_TARGETS
        displayName: Build
        workingDirectory: $(Build.BinariesDirectory)

      - script: |
          set -e
          ctest -V
        displayName: Test
        workingDirectory: $(Build.BinariesDirectory)/build