jobs:
  - job: 'OSX'
    strategy:
      matrix:
        macOS_14:
          image_name: 'macOS-14'
          HG_USE_TBB: 'Off'
        macOS_14_TBB:
          image_name: 'macOS-14'
          HG_USE_TBB: 'On'
    pool:
      vmImage: $(image_name)
    variables:
      CC: clang
      CXX: clang++
    timeoutInMinutes: 360
    steps:

      #- script: |
      #    echo "Removing homebrew for Azure to avoid conflicts with conda"
      #    curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh > ~/uninstall_homebrew
      #    chmod +x ~/uninstall_homebrew
      #    ~/uninstall_homebrew -f -q
      #  displayName: Remove homebrew
      # sudo chown -R $USER $CONDA

      - bash: |
          echo "Downloading and installing Miniconda..."
          curl -LO https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
          bash Miniconda3-latest-MacOSX-x86_64.sh -b -p $HOME/miniconda
          echo "##vso[task.prependpath]$HOME/miniconda/bin"
        displayName: Add conda to PATH

      - script: |
          conda config --set always_yes yes --set changeps1 no
          conda update -q conda
          conda install cmake tbb-devel==2019.9 scikit-learn -c conda-forge
        displayName: Install python packages

      - script: |
          set -e
          mkdir build
          cd build
          MAKE_TARGETS="test_exe higram"
          CMAKE_EXTRA_ARGS="$CMAKE_EXTRA_ARGS -DPython_EXECUTABLE=$HOME/miniconda/bin/python -DTBB_INCLUDE_DIR=$HOME/miniconda/bin/include -DTBB_LIBRARY=$HOME/miniconda/bin/lib -DHG_USE_TBB=$HG_USE_TBB -DHG_UNITY_BUILD=ON -DHG_UNITY_BUILD_BATCH_SIZE=4";
          CMAKE_EXTRA_ARGS="$CMAKE_EXTRA_ARGS -DCMAKE_BUILD_TYPE=Debug"
          cmake $CMAKE_EXTRA_ARGS $(Build.SourcesDirectory)
          make -j2 $MAKE_TARGETS
        displayName: Build
        workingDirectory: $(Build.BinariesDirectory)

      - script: |
          set -e
          ctest -V
        displayName: Test
        workingDirectory: $(Build.BinariesDirectory)/build